language: go

sudo: false

go:
  - "1.11"
  - tip

env:
  - GO111MODULE=on

install: true

before_script:
  - go get ./...
  - go vet ./...

script:
  - go test ./... -v -cover -race -coverprofile=profile.out -covermode=atomic
after_script:
  - cat profile.out >> coverage.txt
  - bash <(curl -s https://codecov.io/bash)
