language: go
sudo: false
go:
  - 1.8
  - 1.9
  - tip
before_script:
  - go vet ./...
script:
  - go build
  - go test ./... -v -cover -race -coverprofile=coverage.txt -covermode=atomic
after_script:
  - bash <(curl -s https://codecov.io/bash)
