version: '3.3'
services:
  proxy:
    image: golang:latest
    container_name: proxy
    environment:
      - BIN=proxy
      - GRPC_TRACE=all
      - GRPC_VERBOSITY=DEBUG
    env_file:
      - cmd/proxy/.env
    expose:
      - "3000"
    ports:
      - "2345:2345"
      - "3000:3000"
    volumes:
      - ./:/go/src/${PKG}
    networks:
      - proxy_tier
    depends_on:
      - auth
      - user
    working_dir: /go/src/${PKG}
    command: go run cmd/proxy/main.go
    # uncomment below to enable debugger
    # command: sh bin/dev.sh
    # privileged: true

  auth:
    image: golang:latest
    container_name: auth
    environment:
      - BIN=auth
      - GRPC_TRACE=all
      - GRPC_VERBOSITY=DEBUG
    env_file:
      - cmd/auth/.env
    expose:
      - "3001"
    ports:
      - "3001:3001"
    volumes:
      - ./:/go/src/${PKG}
    networks:
      - proxy_tier
      - back_tier
    healthcheck:
      test: curl -f http://localhost:3001 || exit 1
    working_dir: /go/src/${PKG}
    command: go run cmd/auth/main.go

  user:
    image: golang:latest
    container_name: user
    environment:
      - BIN=user
      - GRPC_TRACE=all
      - GRPC_VERBOSITY=DEBUG
    env_file:
      - cmd/user/.env
    expose:
      - "3002"
    ports:
      - "3002:3002"
    volumes:
      - ./:/go/src/${PKG}
    networks:
      - proxy_tier
      - back_tier
    healthcheck:
      test: curl -f http://localhost:3001 || exit 1
    working_dir: /go/src/${PKG}
    command: go run cmd/user/main.go

  godoc:
    image: golang:latest
    container_name: godoc
    expose:
      - "6060"
    ports:
      - "6060:6060"
    volumes:
      - ./:/go/src/${PKG}
    command: godoc -http=:6060 -index=true -play

networks:
  proxy_tier:
    driver: bridge
  back_tier:
    driver: bridge