version: '3.3'
services:
  apiserver:
    image: golang:latest
    container_name: apiserver
    environment:
      - BIN=apiserver
    env_file:
      - cmd/apiserver/.env
    expose:
      - "${SERVER_PORT}"
    ports:
      - "2345:2345"
    volumes:
      - ./:/go/src/${PKG}
    networks:
      - proxy_tier
    working_dir: /go/src/${PKG}
    command: sh dev.sh
    privileged: true

  userserver:
    image: golang:latest
    container_name: userserver
    environment:
      - BIN=userserver
    env_file:
      - cmd/userserver/.env
    expose:
      - "${SERVER_PORT}"
    ports:
      - "5001:5001"
    volumes:
      - ./:/go/src/${PKG}
    networks:
      - proxy_tier
      - back_tier
    working_dir: /go/src/${PKG}
    command: go run cmd/userserver/main.go
    privileged: true

  localstack:
    image: localstack/localstack
    container_name: localstack
    environment:
      - SERVICES=dynamodb:${DYNAMODB_PORT}
    ports:
      - "8080:8080"
      - "4567-4582:4567-4582"
    networks:
      - back_tier

networks:
  proxy_tier:
    driver: bridge
  back_tier:
    driver: bridge
