{{- if .Values.ingress.tls -}}
{{- $fullName := include "app.fullname" . -}}
{{- $chartName := include "app.fullname" . -}}
{{- $appName := include "app.fullname" . -}}
{{- $releaseName := .Release.Name -}}
{{- $releaseService := .Release.Service -}}
{{- $values := .Values }}
{{- range .Values.ingress.tls -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}
  {{- if hasKey $values "namespace" }}
  namespace: {{ $values.namespace }}
  {{- end }}
  labels:
    helm.sh/chart: {{ $chartName }}
    app.kubernetes.io/name: {{ $appName }}
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: {{ $releaseService }}
spec:
  secretName: {{ .secretName }}
  {{- with .hosts }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: {{ $values.ingress.class }}
      {{- with .hosts }}
      domains:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  issuerRef:
    name: {{ $values.ingress.issuerName }}
    kind: {{ $values.ingress.issuerKind }}
---
{{- end }}
{{- end }}
