{{- if .Values.secret }}
apiVersion: v1
kind: Secret
type: {{ .Values.secret.type }}
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "app.name" . }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
  {{- toYaml .Values.secret.data | nindent 2 }}
{{- end }}