magic-namespace:
  namespace: go-api-boilerplate
  tiller:
    enabled: false
  namespaceAttributes:
    labels:
      cert-manager.io/disable-validation: "true"
  ## Optional additional ServiceAccounts
  serviceAccounts:
    - goapiboilerplate
    # Optional additional RoleBindings. It is a good idea to specify at least one
    # to grant administrative permissions to a user or group.
  roleBindings:
    - name: admin-group-admin
      role:
        ## Valid values are "Role" or "ClusterRole"
        kind: ClusterRole
        name: admin
      subject:
        ## Valid values are "User", "Group", or "ServiceAccount"
        kind: Group
        name: <group>
