dependencies:
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: pubsub
    condition: pubsub.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: auth
    condition: auth.enabled
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: user
    condition: user.enabled
# AWS localstack (for local development)
  - name: microservice
    version: 0.1.0
    repository: "file://../microservice"
    alias: localstack
    condition: localstack.enabled
# External charts: https://github.com/helm/charts/blob/master/stable
  - name: kubernetes-dashboard
    version: 1.2.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: kubernetes-dashboard.enabled
  - name: heapster
    version: 0.3.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: heapster.enabled
  - name: cert-manager
    version: v0.5.2
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: cert-manager.enabled
  - name: nginx-ingress
    version: 1.1.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: nginx-ingress.enabled
  - name: mysql
    version: 0.13.0
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: mysql.enabled
  - name: phpmyadmin
    version: 2.0.4
    repository: https://kubernetes-charts.storage.googleapis.com/
    condition: phpmyadmin.enabled
