ingress:
  enabled: true
  issuerName: letsencrypt
  issuerKind: Issuer
  class: nginx
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/secure-backends: "true"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: go-api-boilerplate.local
      paths:
        - path: /
          backend:
            serviceName: kubernetes-dashboard
            servicePort: 443
        - path: /localstack
          backend:
            serviceName: go-api-boilerplate-localstack
            servicePort: 4567
        - path: /auth
          backend:
            serviceName: go-api-boilerplate-auth
            servicePort: 3000
        - path: /users
          backend:
            serviceName: go-api-boilerplate-user
            servicePort: 3000
  tls:
    - secretName: go-api-boilerplate-tls
      hosts:
        - go-api-boilerplate.local

issuer:
  enabled: true
  name: letsencrypt
  kind: Issuer
  server: https://acme-v02.api.letsencrypt.org/directory
  email: example@gmail.com
  secretName: go-api-boilerplate-tls
  http01: true

cert-manager:
  ingressShim:
    defaultIssuerName: letsencrypt
    defaultIssuerKind: Issuer
  # @TODO: Ucomment after first deploy. For details see: https://github.com/jetstack/cert-manager/issues/870
  # createCustomResource: false

kubernetes-dashboard:
  enableInsecureLogin: true
  fullnameOverride: 'kubernetes-dashboard'
  extraArgs:
    - '--heapster-host=http://heapster.default:8082'

heapster:
  fullnameOverride: 'heapster'

mysql:
  existingSecret: go-api-boilerplate-app
  initializationFiles:
    db.sql: |-
      CREATE DATABASE IF NOT EXISTS goapiboilerplate DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
    user.sql: |-
      CREATE TABLE `users` (
        `distinctId`   INT                                    NOT NULL AUTO_INCREMENT,
        `id`           CHAR(36)                               NOT NULL,
        `emailAddress` VARCHAR(255) COLLATE utf8_general_ci   NOT NULL,
        `facebookId`   VARCHAR(255)                                     DEFAULT NULL,
        `googleId`     VARCHAR(255)                                     DEFAULT NULL,
        PRIMARY KEY (`distinctId`),
        UNIQUE KEY `id` (`id`),
        UNIQUE KEY `emailAddress` (`emailAddress`),
        INDEX `i_facebookId` (`facebookId`),
        INDEX `i_googleId` (`googleId`)
      )
        ENGINE = InnoDB
        DEFAULT CHARSET = utf8
        COLLATE = utf8_bin;

# AWS localstack https://github.com/localstack/localstack
localstack:
  enabled: false
  nameOverride: localstack
  image:
    repository: localstack/localstack
    tag: 0.8.10
    pullPolicy: IfNotPresent
  service:
    ports:
      - name: dynamodb
        internalPort: 4569
        externalPort: 4569
      - name: ui
        internalPort: 4567
        externalPort: 4567
  env:
    - name: SERVICES
      value: "dynamodb:4569"
    - name: PORT_WEB_UI
      value: "4567"

auth:
  nameOverride: auth
  image:
    repository: auth
    tag: latest
    pullPolicy: Never
  service:
    ports:
      - name: http
        internalPort: 3000
        externalPort: 3000
      - name: grpc
        internalPort: 3001
        externalPort: 3001
  envFromSecretRef: go-api-boilerplate-app
  env:
    - name: ENV
      valueFrom:
        configMapKeyRef:
          key: ENV
          name: go-api-boilerplate-app
    - name: ORIGINS
      valueFrom:
        configMapKeyRef:
          key: ORIGINS
          name: go-api-boilerplate-app
    - name: HOST
      valueFrom:
        configMapKeyRef:
          key: HOST
          name: go-api-boilerplate-app
    - name: PORT_HTTP
      valueFrom:
        configMapKeyRef:
          key: PORT_HTTP
          name: go-api-boilerplate-app
    - name: PORT_GRPC
      valueFrom:
        configMapKeyRef:
          key: PORT_GRPC
          name: go-api-boilerplate-app
    - name: USER_HOST
      value: go-api-boilerplate-user
    - name: USER_PORT_GRPC
      valueFrom:
        configMapKeyRef:
          key: PORT_GRPC
          name: go-api-boilerplate-app
  readiness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    httpGet:
      path: /readiness
      port: 3000
  liveness:
    initialDelaySeconds: 20
    httpGet:
      path: /healthz
      port: 3000

user:
  nameOverride: user
  image:
    repository: user
    tag: latest
    pullPolicy: Never
  service:
    ports:
      - name: http
        internalPort: 3000
        externalPort: 3000
      - name: grpc
        internalPort: 3001
        externalPort: 3001
  envFromSecretRef: go-api-boilerplate-app
  env:
    - name: ENV
      valueFrom:
        configMapKeyRef:
          key: ENV
          name: go-api-boilerplate-app
    - name: ORIGINS
      valueFrom:
        configMapKeyRef:
          key: ORIGINS
          name: go-api-boilerplate-app
    - name: HOST
      valueFrom:
        configMapKeyRef:
          key: HOST
          name: go-api-boilerplate-app
    - name: PORT_HTTP
      valueFrom:
        configMapKeyRef:
          key: PORT_HTTP
          name: go-api-boilerplate-app
    - name: PORT_GRPC
      valueFrom:
        configMapKeyRef:
          key: PORT_GRPC
          name: go-api-boilerplate-app
    - name: DB_HOST
      value: 'go-api-boilerplate-mysql'
    - name: DB_PORT
      value: '3306'
    - name: DB_USER
      value: 'root'
    - name: DB_PASS
      valueFrom:
        secretKeyRef:
          key: mysql-root-password
          name: go-api-boilerplate-app
    - name: DB_NAME
      value: 'goapiboilerplate'
    - name: AWS_REGION
      valueFrom:
        configMapKeyRef:
          key: AWS_REGION
          name: go-api-boilerplate-app
    - name: AWS_ENDPOINT
      valueFrom:
        configMapKeyRef:
          key: AWS_ENDPOINT
          name: go-api-boilerplate-app
  readiness:
    initialDelaySeconds: 20
    timeoutSeconds: 5
    httpGet:
      path: /readiness
      port: 3000
  liveness:
    initialDelaySeconds: 20
    httpGet:
      path: /healthz
      port: 3000

secret:
  type: Opaque
  data:
    SECRET: changeme
    mysql-root-password: password
    mysql-password: password

configMap:
  data:
    ENV: development
    ORIGINS: go-api-boilerplate.local|localhost|0.0.0.0|127.0.0.1
    HOST: '0.0.0.0'
    PORT_HTTP: '3000'
    PORT_GRPC: '3001'
    AWS_REGION: 'us-east-1'
    AWS_ENDPOINT: 'http://go-api-boilerplate-localstack:4569'
