# override this values in an application chart /helm-chart/values.yml
# for more info read https://github.com/helm/helm/blob/master/docs/chart_template_guide/subcharts_and_globals.md

replicaCount: 1

image:
  repository: user
  tag: latest
  pullPolicy: Never

nameOverride: ""
fullnameOverride: ""

service:
  name: user
  type: ClusterIP
  externalPort: 3000
  internalPort: 3000

secret:
  type: Opaque
  data:
    SECRET: changeme

configMap:
  data:
    ENV: development
    HOST: '0.0.0.0'
    PORT: '3000'

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
