apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ include "helm-chart.fullname" . }}
  helm.sh/chart: {{ include "helm-chart.chart" . }}
  app.kubernetes.io/name: {{ include "helm-chart.name" . }}
  app.kubernetes.io/instance: {{ .Release.Name }}
  app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  secretName: {{ .Values.cert.secretName }}
  {{- with .Values.cert.domains }}
  dnsNames:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  acme:
    config:
    - http01:
        ingressClass: {{ .Values.cert.ingressClass }}
      {{- with .Values.cert.domains }}
      domains:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  issuerRef:
    name: {{ .Values.cert.issuerName }}
    kind: {{ .Values.cert.issuerKind }}
