apiVersion: v1
kind: Service
metadata:
  name: {{ include "microservice.fullname" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "microservice.name" . }}
    helm.sh/chart: {{ include "microservice.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "microservice.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  {{- range .Values.service.ports }}
  - port: {{ .externalPort }}
    name: {{ .name }}
    targetPort: {{ .internalPort }}
  {{- end }}
