apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  ports:
  - port: 3000
    targetPort: auth-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 3
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: local/auth
        imagePullPolicy: Never
        ports:
        - name: auth-service
          containerPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: default
data:
  ENV: development
  HOST: proxy-service
  PORT: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
type: Opaque
data:
  SECRET: changeme
