apiVersion: v1
kind: Service
metadata:
  name: auth
  labels:
    app: auth
spec:
  ports:
    - port: 80
  selector:
    app: auth
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: auth
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: auth
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: auth
        tier: frontend
    spec:
      containers:
      - image: auth:4.8-apache
        name: auth
        env:
        - name: auth_DB_HOST
          value: auth-mysql
        - name: auth_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 80
          name: auth
        volumeMounts:
        - name: auth-persistent-storage
          mountPath: /var/www/html
      volumes:
      - name: auth-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
