apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
  - port: 3000
    targetPort: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 3
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: local/user
        imagePullPolicy: Never
        ports:
        - name: user-service
          containerPort: 3000
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: default
data:
  ENV: development
  HOST: proxy-service
  PORT: 3000
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
type: Opaque
data:
  SECRET: changeme
