apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user
  ports:
  - port: 3000
    targetPort: user-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-deployment
  labels:
    app: user
spec:
  selector:
    matchLabels:
      app: user
  replicas: 1
  template:
    metadata:
      labels:
        app: user
    spec:
      containers:
      - name: user
        image: user:latest
        imagePullPolicy: Never
        ports:
        - name: user-service
          containerPort: 3000
        envFrom:
        - secretRef:
            name: user-secret
        - configMapRef:
            name: user-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
  namespace: default
data:
  ENV: development
  HOST: '0.0.0.0'
  PORT: '3000'
---
apiVersion: v1
kind: Secret
metadata:
  name: user-secret
type: Opaque
data:
  SECRET: changeme
