# This is example k8 deployment file
# @deprecated use helm chart instead `make helm-history BIN=proxy`
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
spec:
  selector:
    app: proxy
  ports:
  - port: 3000
    targetPort: proxy-service
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: proxy-deployment
  labels:
    app: proxy
spec:
  selector:
    matchLabels:
      app: proxy
  replicas: 1
  template:
    metadata:
      labels:
        app: proxy
    spec:
      containers:
      - name: proxy
        image: proxy:latest
        imagePullPolicy: Never
        ports:
        - name: proxy-service
          containerPort: 3000
        envFrom:
        - secretRef:
            name: proxy-secret
        - configMapRef:
            name: proxy-config
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /readiness
            port: 3000
          initialDelaySeconds: 20
          timeoutSeconds: 5
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
  namespace: default
data:
  ENV: development
  HOST: '0.0.0.0'
  PORT: '3000'
  USER_SERVICE_HOST: user-service
  USER_SERVICE_PORT: '3000'
  AUTH_SERVICE_HOST: auth-service
  AUTH_SERVICE_PORT: '3000'
  CERT_DIR_CACHE: certs
  ORIGINS: localhost|0.0.0.0|127.0.0.1
---
apiVersion: v1
kind: Secret
metadata:
  name: proxy-secret
type: Opaque
data:
  SECRET: changeme