proxy:
  nameOverride: proxy
  image:
    repository: proxy
    tag: latest
    pullPolicy: Never
  service:
    # type: LoadBalancer
    ports:
      - name: grpc
        internalPort: 3000
        externalPort: 3000
      # - name: http
      #   internalPort: 3000
      #   externalPort: 80
      # - name: https
      #   internalPort: 3000
      #   externalPort: 443
    readiness:
      initialDelaySeconds: 20
      timeoutSeconds: 5
      httpGet:
        path: /readiness
        port: 3000
    liveness:
      initialDelaySeconds: 20
      httpGet:
        path: /healthz
        port: 3000
  secret:
    data:
      SECRET: changeme
  configMap:
    data:
      ENV: development
      HOST: '0.0.0.0'
      PORT: '3000'
      USER_SERVICE_HOST: go-api-boilerplate-app-user
      USER_SERVICE_PORT: '3000'
      AUTH_SERVICE_HOST: go-api-boilerplate-app-auth
      AUTH_SERVICE_PORT: '3000'
      CERT_DIR_CACHE: certs
      ORIGINS: localhost|0.0.0.0|127.0.0.1